### PR TITLE
Side bar order stats#321

### LINKED ISSUE #321: Home page : Statistics > My Orders is not 0 for new user
To reproduce:
- Sign up as new user
- User is logged in 

Expected:
- "Statistics > My Orders" count should be 0

Actual:
- "Statistics > My Orders" was 2

Also, I expected the icon to be clickable and take me to those two orders

### PR DESCRIPTION
**Pull request by Jasonvdb**
Closes #321

### CODE REVIEW

File: src/components/pages/venues/ViewVenue.js [hunk 1]
```diff
@@ -102,9 +102,19 @@ class ViewVenue extends Component {
 		}
 
 		return events.map(event => {
+			//TODO remove this. It's a temp fix until bn-api changes this field name.
```
Comment (Krakaw) [inline src/components/pages/venues/ViewVenue.js]: This is coming in big-neon/bn-api#600
