### PR TITLE
Fee schedule validation error#1070

### LINKED ISSUE #1070: Fee Schedules - Unable to add fee schedule for new org
See: https://cl.ly/eac78f074f05

Add fees, click update fee schedule and the values fail to save and UI shows NaN values

### PR DESCRIPTION
**Pull request by Jasonvdb**
Closes #1070

### CODE REVIEW

File: src/components/pages/admin/organizations/sections/FeeSchedule.js [hunk 1]
```diff
@@ -178,12 +214,15 @@ class FeeSchedule extends Component {
...
-			if (index > 0 && min_price <= ranges[index - 1].min_price) {
-				rangesErrors[
-					index
-				].min_price = `Minimum price must be more than ${ranges[
-					index - 1
-				].min_price.toFixed(2)}`;
+
+			const previousMinPrice = ranges[index - 1] ? Number(ranges[index - 1].min_price) : 0;
+			if (index > 0 && min_price <= previousMinPrice) {
+				console.log(`${index} > 0 && ${min_price} <= ${previousMinPrice}`);
```
Comment (Krakaw) [inline src/components/pages/admin/organizations/sections/FeeSchedule.js]:
```suggestion
```
